name: appthreat scan

on: push

jobs:
  appthreat:
    name: appthreat scan
    runs-on:  self-hosted

    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: python,java

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports