name: codeql aciton

on:
  push:
    branches:    
      # Push events on main branch
      - main

jobs:
  test-workflow:
    name: codeql workflow
    runs-on: self-hosted

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


        # this needs the PAT that is added and not the default token       
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      






