name: APPTHREAT SAST Scan
on: [push]

jobs:
  APPTHREAT_SAST_Scan:
    runs-on: self-hosted
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Scan Action
      uses: AppThreat/sast-scan-action@v1.0.0
      with:
        output: reports
        type: python

    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: reports